account/urls.py
from django.urls import path
from .controllers.signup import SubscribeView
from .controllers.signin import SigninView
from .controllers.logout import LogoutView
from .controllers.search import AuthView
from .controllers.activate import userActivationView
from .controllers.pwdreset import resetPwdView, userVerifyView
from .controllers.resMessages import AuthMsgView
from .controllers.editpassword import resetPwdEditView

app_name = "account"

urlpatterns = [
    path('auth/', AuthView, name='auth'),
    path('status/', AuthMsgView, name='authmsg'),
    path('reset/', resetPwdView, name='reset1'),
    path('reset/identifier?<uidcoded><token>/', resetPwdEditView, name='reset2'),
    path('signin/', SigninView, name='signin'),
    path('signin/verify?<uidcoded><token>/', userVerifyView, name='signinauth'),
    path('signin/activate?<uidcoded><token>/', userActivationView, name='activate'),
    path('subscribe/', SubscribeView, name='subscribe'),
    path('logout/', LogoutView, name='logout'),
]

core/urls.py
from django.urls import path
from .views import LandpageView, HomepageView, BlogView, PostView

app_name = "core"

urlpatterns = [
    path("", LandpageView, name="index"),
    path("home/", HomepageView, name="home"),
    path("logs/", BlogView, name="blog"),
    path("logs/<int:pk>/<slug:slug>/", PostView, name="article"),
    # path("legal/", LegalView.as_view(), name="legal"),
]

pwa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/',include('account.urls')),
    path('', include('core.urls')),
    # path('shop/', include('store.urls')),
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.errorviews.page404'
handler500 = 'core.errorviews.page500'
handler400 = 'core.errorviews.page404' # Bad request
# handler403 = 'mysite.views.my_custom_permission_denied_view' # Permission denied

core/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.translation import gettext_lazy as _

User = get_user_model()

class Event(models.Model):
    id = models.BigAutoField(primary_key=True)
    date = models.DateField(auto_now_add=False)
    name = models.CharField(max_length=100, blank=False)
    slug = models.CharField(max_length = 500)
    location = models.CharField(max_length=100, blank=False)
    poster = models.ImageField(upload_to='core/events/%Y/%m/')
    posterURI = models.URLField()
    url = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-date']
        db_table = 'event'

class ArticleCategory(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length = 500)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'article_category'

class ArticleTag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length = 500)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'article_tag'

class ArticleStat(models.Model):
    IPAddres= models.GenericIPAddressField(default='0.0.0.0')
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    # session = models.CharField(max_length=40, null=True)
    device = models.CharField(max_length=400 ,default='null')
    visited = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{0} in {1} article'.format(self.IPAddres,self.article.title)

    class Meta:
        ordering = ['-visited']
        db_table = 'article_stat'

class Stat(models.Model):
    IPAddres= models.GenericIPAddressField(default='0.0.0.0')
    page = models.CharField(max_length=40, null=True)
    device = models.CharField(max_length=400 ,default='null')
    visited = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-page']
        db_table = 'stats'

class Article(models.Model):
    id = models.BigAutoField(primary_key=True)
    featureimage = models.ImageField(upload_to='core/article/%Y/%m/')
    featureimageURI = models.URLField(blank=True, null=True)
    title = models.CharField(max_length=500)
    slug = models.CharField(max_length=500)
    tags = models.ManyToManyField(ArticleTag, related_name='tags')
    category = models.ForeignKey(ArticleCategory, related_name='articles', on_delete=models.PROTECT)
    writer = models.CharField(max_length=100, default = 'Leroy Buliro')
    credit = models.CharField(max_length=700, blank=True, null=True)
    publishdate = models.DateField(auto_now_add=False)
    extract = models.CharField(max_length=2000, blank=True, null=True)
    content = RichTextField(config_name='full_editor', blank=True, null=True)
    likes = models.PositiveIntegerField(default=0)
    POST_STATUS = (
        ('D', 'Draft'),
        ('P', 'Publish'),
    )
    status = models.CharField(max_length=10, choices=POST_STATUS)

    def get_absolute_url(self):
        return f'/logs/{self.id}/{self.slug}/'

    @property
    def url(self):
        return f'/logs/{self.id}/{self.slug}/'

    @property
    def viewCount(self):
        return ArticleStat.objects.filter(article=self).count()

    @property
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs
    
    @property
    def commentCount(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        qs = Comment.objects.filter(content_type=content_type, object_id=self.id).count()
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publishdate']
        db_table = 'article'

class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # post = models.ForeignKey(Article, related_name='replies', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    content = models.TextField(max_length=420, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_flagged = models.BooleanField(default=False)

    objects = CommentManager()
    
    def replies(self):
        return Comment.objects.filter(parent=self).order_by('timestamp')

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

    class Meta:
        ordering = ['-timestamp']
        db_table = 'comments'

class Feedback(models.Model):
    id = models.BigAutoField(primary_key=True)
    postdate = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=500, blank=False)
    ratings = models.IntegerField()
    source = models.CharField(max_length = 200, blank=False)

    class Meta:
        ordering = ['-postdate']
        db_table = 'feedback'

class Mailing(models.Model):
    id = models.BigAutoField(primary_key=True)
    date = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(verbose_name=_('Email'), max_length=100)

    class Meta:
        db_table = 'mailing'

core/forms.py
from core.models import Feedback, Mailing
from django import forms

class commentForm(forms.Form):
    parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(
        widget=forms.Textarea(attrs={
            'rows':4, 
            'placeholder': 'This conversation is moderated.'
        }), 
        min_length=1, 
        max_length=420
    )

class feedbackForm(forms.ModelForm):
    content = forms.CharField (min_length=1, max_length=500)
    ratings = forms.RadioSelect()

    class Meta:
        model = Feedback
        fields = ['content', 'ratings',]

class mailingForm(forms.ModelForm):
    email = forms.EmailField ()

    class Meta:
        model = Mailing
        fields = ['email',]

core/views.py
from core.models import Comment, Article, ArticleStat, Stat
from core.forms import feedbackForm, commentForm, mailingForm
from django.shortcuts import redirect, render, get_object_or_404
from core.models import Stat
from core.utils import get_client_ip
from django.contrib import messages
from django.urls import reverse
from datetime import datetime
# from django.contrib.auth.decorators import login_required
# from django.conf import settings

def LandpageView(request):
    context = {}
    request.session['next'] = '/'

    ip = get_client_ip(request)
    Stat.objects.get_or_create(
        page="landing_page",
        IPAddres=ip,
        device = request.META.get('HTTP_USER_AGENT')
    )

    return render(request, 'core/landpage.html', context)



def HomepageView(request):
    context = {}
    context['current_year'] = datetime.now().year
    context['featured'] = Article.objects.filter(status='P').order_by('-publishdate').first()
    context['articles'] = Article.objects.filter(status='P').order_by('-publishdate')[1:]
    request.session['next'] = '/home/'

    ip = get_client_ip(request)
    Stat.objects.get_or_create(
        page="home",
        IPAddres=ip,
        device = request.META.get('HTTP_USER_AGENT')
    )

    if 'submitfeedback' in request.POST:
        form = feedbackForm(request.POST)
        if form.is_valid(): 
            form.instance.source = 'home'
            form.save()
            messages.add_message(request,messages.SUCCESS, 'Thank you for your feedback')
            return redirect(reverse('core:home'))

    if 'mailing' in request.POST:
        form = mailingForm(request.POST)
        if form.is_valid(): 
            form.save()
            messages.add_message(request,messages.SUCCESS, 'Successfully submitted')
            return redirect(reverse('core:home'))

    return render(request, 'core/homepage.html', context)

def BlogView(request):
    context = {}
    context['current_year'] = datetime.now().year
    context['articles'] = Article.objects.filter(status='P').order_by('-publishdate')
    request.session['next'] = '/logs/'

    ip = get_client_ip(request)
    Stat.objects.get_or_create(
        page="blog",
        IPAddres=ip,
        device = request.META.get('HTTP_USER_AGENT')
    )

    if 'submitfeedback' in request.POST:
        form = feedbackForm(request.POST)
        if form.is_valid(): 
            form.instance.source = 'blog'
            form.save()
            messages.add_message(request,messages.SUCCESS, 'Thank you for your feedback')
            return redirect(reverse('core:blog'))

    if 'mailing' in request.POST:
        form = mailingForm(request.POST)
        if form.is_valid(): 
            form.save()
            messages.add_message(request,messages.SUCCESS, 'Successfully submitted')
            return redirect(reverse('core:blog'))

    return render(request, 'core/blog.html', context)

def PostView(request, pk, slug):
    context = {}
    context['current_year'] = datetime.now().year
    obj = get_object_or_404(Article, id=pk, slug=slug)
    context['article'] = obj
    next = obj.get_absolute_url()
    request.session['next'] = next

    ip = get_client_ip(request)
    post_details=Article.objects.get(pk=obj.pk)
    ArticleStat.objects.get_or_create(
        article=post_details,
        IPAddres=ip,
        device = request.META.get('HTTP_USER_AGENT')
    )
    
    form = commentForm(request.POST or None)
    context['form'] = form
    if 'submitcomment' in request.POST:
        if form.is_valid():
            user = request.user
            content = form.cleaned_data.get('content')
            content_type = obj.get_content_type
            # content_type = ContentType.objects.get(model=c_type)
            object_id = obj.pk
            parent = None

            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None

            if parent_id:
                parent_qs = Comment.objects.filter(pk=parent_id)
                if parent_qs.exists() and parent_qs.count() == 1:
                    parent = parent_qs.first()

            Comment.objects.get_or_create(
                user = user,
                content_type = content_type,
                object_id = object_id,
                content = content, 
                parent = parent
            )

            messages.add_message(request,messages.SUCCESS, 'Comment successfully added')
            
            return redirect(reverse('core:article', kwargs={'pk':obj.pk, 'slug':obj.slug}))

    if 'deletecomment' in request.POST:
        comment_id = request.POST.get('comment_id')
        instance = Comment.objects.get(pk=comment_id)
        # instance = get_object_or_404(Comment, pk=comment_id)
        instance.delete()
        messages.add_message(request,messages.SUCCESS, 'Comment successfully deleted')
        return redirect(reverse('core:article', kwargs={'pk':obj.pk, 'slug':obj.slug}))

    if 'submitfeedback' in request.POST:
        form = feedbackForm(request.POST)
        if form.is_valid():
            form.instance.source = obj
            form.save()
            messages.add_message(request,messages.SUCCESS, 'Thank you for your feedback')
            return redirect(reverse('core:article', kwargs={'pk':obj.pk, 'slug':obj.slug}))

    if 'mailing' in request.POST:
        form = mailingForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS, 'Successfully submitted')
            return redirect(reverse('core:article', kwargs={'pk':obj.pk, 'slug':obj.slug}))

    return render(request, 'core/post.html', context)
 

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no, maximum-scale=1.0, user-scalable=no">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/> -->
        <link rel="icon" type="image/png" href="{% static 'core/media/favicon.ico' %}"/>
        <meta name="author" content="Leroy Buliro"/>
        <link rel="canonical" href="https://leroy.buliro.net/">
        <meta name="description" content="This is the official website of Leroy Buliro.">
        <meta name="docsearch:language" content="en">
        {% block head %}
        {% endblock head %}
        <link rel="stylesheet" href="{% static 'core/styles/base.css' %}"/>
        <link rel="stylesheet" href="{% static 'core/styles/feedbackModal.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@graph": [
                {
                    "@id": "#site",
                    "@type": "Website",
                    "name": "Leroy Buliro",
                    "author": "Leroy Buliro",
                    "description": "This is the official website of Leroy Buliro",
                    "url": "https://leroy.buliro.net",
                    "schemaVersion": "10.0",
                    "keywords": "Africa, culture, technology",
                },
                {
                    "@type": "Blog",
                    "isPartOf": "#site",
                    "name": "Logs by Leroy Buliro",
                    "description": "The official blog of Leroy Buliro",
                    "url": "https://leroy.buliro.net/logs/",
                    "keywords": "Africa, culture, technology",
                },
                {
                    "@type": "Podcast",
                    "isPartOf": "#site",
                    "name": "Kubonga, a podcast by Leroy Buliro",
                    "description": "The official podcast of Leroy Buliro",
                    "url": "https://leroy.buliro.net/",
                    "keywords": "culture, technology",
                }
                ]
            }
        </script>
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function(){
                // FEEDBACK MODAL
                document.addEventListener('click', (event)=> {
                    if(event.target.id=="id01"){
                        document.querySelector('#id01').style.display='none';
                    };
                })    
                
                let message = $('.popmessage');
                
                $(document).ready(function(){
                    message.fadeIn(2000)
                    setTimeout(()=>{
                        message.fadeOut(2000)
                    },6000)
                    
                    // Check Radio-box
                    $(".rating input:radio").attr("checked", false);
                    
                    $('.rating input').click(function () {
                        $(".rating span").removeClass('checked');
                        $(this).parent().addClass('checked');
                    });
                });
            });
        </script>
    </head>
    <body>
        {% if messages %}
        {% for message in messages %}
        <div class="popmessage">
            <p class="message">{{ message }}</p>
        </div>
        {% endfor %}
        {% endif %}
        <noscript>
            <div style="display: flex; place-content: center; background-color: tomato;">
                <p style="color: #fff; padding: 7px 0">Javascript not supported on your browser, please enable Javascript in order to fully utilize the website</p>
            </div>
        </noscript>
        <div class="pagebody">
            <nav style="backdrop-filter: blur(10px);">
                <a id="navlogo" href="{% url 'core:home' %}">
                    <img class="logoimg" src="{% static 'core/media/lbwhite.svg' %}" alt="logo" style="width: auto; height: 14px;">
                </a>
                <div class="navmenu">    
                    {% block navmenu %}
                    {% endblock navmenu %}
                </div>
                <div class="access">
                    {% if user.is_authenticated %}
                    <a class="accessbtn" href="{% url 'account:logout' %}">LOG OUT</a>
                    {% else %}
                    <a class="accessbtn" href="{% url 'account:auth' %}">LOG IN</a>
                    {% endif %}
                </div>
                <!-- <div class="menu-btn">
                    <div class="menu-btn__burger"></div>
                </div> -->
            </nav>
            
            {% block page %}
            {% endblock page %}
    
            <div id="id01" class="modal">
                <div class="modal-content" style="max-width:600px"> 
                    <div style="padding: 0.01em;">
                        <p style="text-align: left; color: #000; font-size: x-large; font-weight: bold;">What's on your mind?</p>
                        <span onclick="document.getElementById('id01').style.display='none'" class="modal-close-btn" title="Close">&times;</span>
                    </div>
                    <form class="modal-container" method="POST" action="">{% csrf_token %}
                        <div class="modal-section">
                            <div>
                                <textarea rows="4" type="text" placeholder="We appreciate hearing your thoughts. It helps us make things better." name="content" required></textarea>
                                <p style="color: #929292; font-size: small;">0/500 maximum characters.</p>
                            </div>
                            <div>
                                <p><b>How would you rate your experience with the website?</b></p>
                                <div class="rating">
                                    <span><input type="radio" name="ratings" id="str5" value="5" required><label for="str5">&star;</label></span>
                                    <span><input type="radio" name="ratings" id="str4" value="4" required><label for="str4">&star;</label></span>
                                    <span><input type="radio" name="ratings" id="str3" value="3" required><label for="str3">&star;</label></span>
                                    <span><input type="radio" name="ratings" id="str2" value="2" required><label for="str2">&star;</label></span>
                                    <span><input type="radio" name="ratings" id="str1" value="1" required><label for="str1">&star;</label></span>
                                </div>
                                <div class="ratingdim">
                                    <span>Awful</span>
                                    <span>Wonderful</span>
                                </div>
                            </div>
                            <p>To protect your privacy, don't include your contact info.</p>
                            <div style="display: flex; justify-content: right; padding-top: 12px;">
                                <button class="modal-btn-alt" type="submit" name="submitfeedback">Send feedback</button>
                                <button class="modal-btn" onclick="document.getElementById('id01').style.display='none'" type="button">Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <footer>
            <div class="review">
                <img onclick="document.getElementById('id01').style.display='block'" src="{% static 'core/media/review.svg' %}" alt="send feedback">
            </div>

            <div class="disclaimers">
                <p>Statements on my—websites, social media profiles, presentations, recordings, software, and all other forms of publication 
                    and media—reflect my personal opinions and do not represent the views and/or policies of my employer(s), past or present, 
                    or any other organization with which I may be affiliated. See my legal page to learn about all disclaimers that apply to this site.</p>
            </div>

            <div class="footer">
                <span>© 2017 - {{current_year}} Leroy Buliro.</span>
                <div class="socials">
                    <a href="https://www.twitter.com/leroybuliro/" target="_blank" rel="noreferrer">
                        <img class="slink" src="{% static 'core/media/twitter.svg' %}" alt="find leroy on twitter">
                    </a>
                    <a href="https://www.github.com/leroybuliro/" target="_blank" rel="noreferrer">
                        <img class="slink" src="{% static 'core/media/github.svg' %}" alt="find leroy on github">
                    </a>
                    <a href="https://www.linkedin.com/in/buliro/" target="_blank" rel="noreferrer">
                        <img class="slink" src="{% static 'core/media/linkedin.svg' %}" alt="find leroy on linkedin">
                    </a>
                </div>
            </div>

        </footer>
    </body>
</html>

core/templates/core/blog.html
{% extends "core/base.html" %}
{% load static %}

{% block head %}
<title>Logs | Leroy Buliro</title>
<meta name="description" content="Logs by Leroy Buliro">
<meta name="keyword" content="Tech, Kenya, Nairobi, booze, travel, nightlife, food, lifestyle, culture">
<link rel="stylesheet" href="{% static 'core/styles/blog.css' %}">
{% endblock head %}

{% block navmenu %}
<!-- <a href="{% url 'core:home' %}">HOME</a>
<a id="menuactive" >LOGS</a>
<a href="{% url 'core:home' %}">PODCAST</a> -->
{% endblock navmenu %}

{% block page %}
<div>
    <div class="search">
        <div>
            <input type="text" placeholder="Search">
            <img class="icon_search" src="{% static 'core/media/search.svg' %}" >
        </div>
        <div class="filter">
            <button>Date range</button>
            <button>Category</button>
            <button>Clear filters</button>
        </div>
    </div>
    <div class="blogpage">
        {% if articles %}
        <div id="articles">
            {% for article in articles %}
            <article>
                <a class="articlediv" href="{% url 'core:article' pk=article.id slug=article.slug %}">                    
                    <div class="image">
                        {% if article.featureimageURI %}
                            <img class="blogimage" src="{{ article.featureimageURI }}" alt="{{ article.title }}">
                        {% else %}
                            <img class="blogimage" src="{{ article.featureimage.url }}" alt="{{ article.title }}">
                        {% endif %}
                    </div>
                    <div>
                        <h2>{{ article.title }}</h2>
                        <br>
                        {% if article.extract %}
                            <div class="extract">{{ article.extract }}</div>
                        {% else %}
                            <div class="extract">{{ article.content | safe | truncatewords:20 }}</div>
                        {% endif %}
                        <br>
                        <div class="pubDate">{{ article.publishdate }}</div>
                    </div>
                </a>
            </article>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    
    <!-- <div class="showbtn">
        <button class="loadnext">SHOW MORE</button>
    </div> -->
</div>
{% endblock page %}

core/templates/core/csrfError.html
{% extends "core/error.html" %}
{% load static %}

{% block head %}
<title>Form error</title>
{% endblock head %}

{% block page %}
<div style="margin: 7% 2% 7% 2%;">
    <h3 style="color: #fff;">LOOKS LIKE SOMETHING WENT WRONG</h3>
    <br/>
    <div>
        <p style="color: #fff;">We apologize for any inconvenience. From here you can return to the homepage.</p>
        <br/>
        <a href="{% url 'core:index' %}" style="color: red; font-weight: bolder;">Go Back Home</a>
    </div>
</div>
{% endblock page %}

core/templates/core/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" type="image/png" href="{% static 'core/media/favicon.ico' %}"/>
        <meta name="author" content="Leroy Buliro">
        <link rel="canonical" href="https://leroy.buliro.net/">
        <meta name="description" content="This is the official website of Leroy Buliro.">
        <meta name="docsearch:language" content="en">
        {% block head %}
        {% endblock head %}
        <link rel="stylesheet" href="{% static 'core/styles/error.css' %}">
    </head>
    <body>
        <div id="errContainer">
            <img class="logoimg" src="{% static 'core/media/lbwhite.svg' %}" alt="logo" style="width: auto; height: 20px;">           
            {% block page %}
            {% endblock page %}
        </div>
    </body>
</html>

core/templates/core/legal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Legal | Leroy Buliro</title>
        <link rel="icon" type="image/png" href="{% static 'core/media/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'core/styles/legal.css' %}">
        <script>
            document.addEventListener ('DOMContentLoaded', function(){

                // window.onpopstate = function(event) {
                //     console.log(event.state.section);
                //     showSection(event.state.section);
                // }

                function showSection(section) {

                    // fetch('{section}')

                    document.querySelectorAll('section').forEach(section => {
                        section.style.display = 'none';
                    })
                    // document.querySelector('title').innerHTML = 'Privacy FAQ - The Nairobi Sentinel'
                    document.getElementById(section).style.display = 'block';
                    window.scrollTo(0,0);
                };

                document.querySelectorAll('button').forEach(button  => {
                    button.onclick = function() {

                        const section = this.dataset.section;
                        // history.pushState({section: section}, "", {section});
                        showSection(section);                        
                    }
                });


            });

        </script>
    </head>
    <body>
        <nav class="topnav">
            <a id="navlogo" href="{% url 'core:index' %}">
                <img src="{% static 'core/media/lbwhite.png' %}" alt="logo" >
            </a>
            <div id="navlink" style="display: flex; flex-direction: row; grid-gap: 7px;">
                <button data-section="privacys">Privacy</button>
                <button data-section="terms">Terms</button>
            </div>
        </nav>
        <div class="pagesec">                
            <section id="privacys">
                {% with privacy.0 as privacy %}
                <h1 style="text-align: center;">PRIVACY POLICY</h1>
                <br/>
                <h4>Effective Date: {{ privacy.date }}</h4>
                <br>
                <div class="content">{{ privacy.content | safe }} </div>
                {% endwith %}
            </section>            
            <section id="terms">
                {% with terms.0 as terms %}
                <h1 style="text-align: center;">TERMS OF USE</h1>
                <br/>
                <h4>Effective Date: {{ terms.date }}</h4>
                <br>
                <div class="content">{{ terms.content | safe }}</div>
                {% endwith %}
            </section>
        </div>
        <footer>
            <div>
                <a>© 2022 Leroy Buliro. All rights reserved.</a>
            </div>
        </footer>
    </body>
</html>